# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_todo_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='UserID',
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
