# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_calendo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendo_user',
            name='CalenderView',
        ),
        migrations.RemoveField(
            model_name='calendo_user',
            name='ColorScheme',
        ),
        migrations.RemoveField(
            model_name='calendo_user',
            name='NotificationsFreq',
        ),
    ]
