# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20170304_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendo_user',
            name='ColorScheme',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='calendo_user',
            name='NotificationsFreq',
            field=models.BooleanField(default=False),
        ),
    ]
