# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20170304_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendo_user',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
