# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_calendo_user_isconfirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendo_user',
            name='Name',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
