# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_calendo_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendo_user',
            name='ColorScheme',
        ),
        migrations.RemoveField(
            model_name='calendo_user',
            name='NotificationsFreq',
        ),
        migrations.RemoveField(
            model_name='calendo_user',
            name='isConfirmed',
        ),
    ]
