# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20170305_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(default=b'', max_length=30)),
                ('Code', models.CharField(default=b'', max_length=30)),
                ('IsConfirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
