# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_confirm_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendo_user',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='confirm_email',
            name='Code',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='confirm_email',
            name='Email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
