# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_confirm_email_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendo_user',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
