# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_calendo_user_isconfirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_email',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
    ]
