# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_session'),
        ('webapp', '0013_auto_20170305_1509'),
    ]

    operations = [
    ]
