# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_merge_20170306_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='BirthDate',
            new_name='DeathDate',
        ),
    ]
