# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20170306_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default=b'', max_length=40),
        ),
    ]
