# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20170306_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='EstimateTime',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default=b'', max_length=160),
        ),
    ]
