# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20170306_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='EstimateTime',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
