# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_todo_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Description',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='todo',
            name='DueDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='EndTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='EstimateTime',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='todo',
            name='Location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='StartTime',
            field=models.TimeField(null=True),
        ),
    ]
