# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20170311_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='StartTime',
        ),
    ]
