# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20170314_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='IsScheduled',
            field=models.IntegerField(default=0),
        ),
    ]
